aminoacid_data = {
    'A': {'name': 'Alanine', 'alpha_helix': 0.85, 'beta_folded': 0.05, 'loop': 0.1},
    'R': {'name': 'Arginine', 'alpha_helix': 0.2, 'beta_folded': 0.1, 'loop': 0.7},
    'N': {'name': 'Asparagine', 'alpha_helix': 0.4, 'beta_folded': 0.1, 'loop': 0.5},
    'D': {'name': 'Aspartic Acid', 'alpha_helix': 0.1, 'beta_folded': 0.2, 'loop': 0.7},
    'C': {'name': 'Cysteine', 'alpha_helix': 0.05, 'beta_folded': 0.1, 'loop': 0.85},
    'Q': {'name': 'Glutamine', 'alpha_helix': 0.3, 'beta_folded': 0.2, 'loop': 0.5},
    'E': {'name': 'Glutamic Acid', 'alpha_helix': 0.1, 'beta_folded': 0.3, 'loop': 0.6},
    'G': {'name': 'Glycine', 'alpha_helix': 0.5, 'beta_folded': 0.1, 'loop': 0.4},
    'H': {'name': 'Histidine', 'alpha_helix': 0.3, 'beta_folded': 0.2, 'loop': 0.5},
    'I': {'name': 'Isoleucine', 'alpha_helix': 0.8, 'beta_folded': 0.05, 'loop': 0.15},
    'L': {'name': 'Leucine', 'alpha_helix': 0.7, 'beta_folded': 0.1, 'loop': 0.2},
    'K': {'name': 'Lysine', 'alpha_helix': 0.1, 'beta_folded': 0.2, 'loop': 0.7},
    'M': {'name': 'Methionine', 'alpha_helix': 0.6, 'beta_folded': 0.1, 'loop': 0.3},
    'F': {'name': 'Phenylalanine', 'alpha_helix': 0.7, 'beta_folded': 0.1, 'loop': 0.2},
    'P': {'name': 'Proline', 'alpha_helix': 0.2, 'beta_folded': 0.1, 'loop': 0.7},
    'S': {'name': 'Serine', 'alpha_helix': 0.4, 'beta_folded': 0.1, 'loop': 0.5},
    'T': {'name': 'Threonine', 'alpha_helix': 0.5, 'beta_folded': 0.1, 'loop': 0.4},
    'W': {'name': 'Tryptophan', 'alpha_helix': 0.6, 'beta_folded': 0.1, 'loop': 0.3},
    'Y': {'name': 'Tyrosine', 'alpha_helix': 0.4, 'beta_folded': 0.2, 'loop': 0.4},
    'V': {'name': 'Valine', 'alpha_helix': 0.8, 'beta_folded': 0.05, 'loop': 0.15},
}

codons_based_on_amino = {
    'A': ['GCU', 'GCC', 'GCA', 'GCG'],
    'R': ['CGU', 'CGC', 'CGA', 'CGG', 'AGA', 'AGG'],
    'N': ['AAU', 'AAC'],
    'D': ['GAU', 'GAC'],
    'C': ['UGU', 'UGC'],
    'Q': ['CAA', 'CAG'],
    'E': ['GAA', 'GAG'],
    'G': ['GGU', 'GGC', 'GGA', 'GGG'],
    'H': ['CAU', 'CAC'],
    'I': ['AUU', 'AUC', 'AUA'],
    'L': ['UUA', 'UUG', 'CUU', 'CUA', 'CUG', 'CUC'],
    'K': ['AAA', 'AAG'],
    'M': ['AUG'],
    'F': ['UUU', 'UUC'],
    'P': ['CCU', 'CCC', 'CCA', 'CCG'],
    'S': ['UCU', 'UCC', 'UCA', 'UCG'],
    'T': ['ACU', 'ACC', 'ACA', 'ACG'],
    'W': ['UGG'],
    'Y': ['UAU', 'UAC'],
    'V': ['GUU', 'GUC', 'GUA', 'GUG']
}

aminos_based_on_codon = {
    'AUG': 'M',                                                                   ## KNOWN as Start for a given GEN
    'UUU': 'F', 'UUC': 'F',
    'UUA': 'L', 'UUG': 'L', 'CUU': 'L', 'CUA': 'L', 'CUG': 'L', 'CUC': 'L',
    'AUU': 'I', 'AUC': 'I', 'AUA': 'I',
    'GUU': 'V', 'GUC': 'V', 'GUA': 'V', 'GUG': 'V',
    'UCU': 'S', 'UCC': 'S', 'UCA': 'S', 'UCG': 'S',
    'CCU': 'P', 'CCC': 'P', 'CCA': 'P', 'CCG': 'P',
    'ACU': 'T', 'ACC': 'T', 'ACA': 'T', 'ACG': 'T',
    'GCU': 'A', 'GCC': 'A', 'GCA': 'A', 'GCG': 'A',
    'UAU': 'Y', 'UAC': 'Y',
    'CAU': 'H', 'CAC': 'H',
    'CAA': 'Q', 'CAG': 'Q',
    'AAU': 'N', 'AAC': 'N',
    'AAA': 'K', 'AAG': 'K',
    'GAU': 'D', 'GAC': 'D',
    'GAA': 'E', 'GAG': 'E',
    'UGU': 'C', 'UGC': 'C',
    'UGG': 'W',
    'CGU': 'R', 'CGC': 'R', 'CGA': 'R', 'CGG': 'R', 'AGA': 'R', 'AGG': 'R',
    'AGU': 'S', 'AGC': 'S',
    'GGU': 'G', 'GGC': 'G', 'GGA': 'G', 'GGG': 'G',
    'UAA': '-', 'UAG': '-', 'UGA': '-'                                            ## KNOWN as Stop for a given GEN
}